default_platform(:ios)

import("ios.rb")

before_all do |lane, options|
    skip_docs
	read_ios_params(options)
end

platform :ios do

  desc "Build & deploy to Firebase"
  lane :firebase_deploy do
     build_adhoc_app
     firebase_app_deploy
  end

  desc "Build & deploy to PlayStore"
  lane :appstore_deploy do
     build_appstore_app
     # TODO: Yet to work on it
     # appstore_app_deploy
  end

end
