name: Setup Apple certificate and provisioning profile
description: 'Setup Apple certificate and provisioning profile'

inputs:
  CERTIFICATE_BASE64:
    description: "Provide build certificate .p12 file content"
    required: true
  CERTIFICATE_PASSWORD:
    description: "Provide build certificate .p12 file password"
    required: true
  PROVISION_PROFILE_BASE64:
    description: "Provide build provision profile"
    required: true
  KEYCHAIN_PASSWORD:
    description: "KEYCHAIN_PASSWORD"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install the Apple certificate and provisioning profile
      env:
        CERTIFICATE_BASE64: ${{ inputs.CERTIFICATE_BASE64 }}
        CERTIFICATE_PASSWORD: ${{ inputs.CERTIFICATE_PASSWORD }}
        PROVISION_PROFILE_BASE64: ${{ inputs.PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ inputs.KEYCHAIN_PASSWORD }}
      shell: bash
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PROVISION_PROFILE_PATH=$RUNNER_TEMP/build_provision_profile.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain
        
        # import certificate and provisioning profile from secrets
        echo -n "$CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
        echo -n "$PROVISION_PROFILE_BASE64" | base64 --decode --output $PROVISION_PROFILE_PATH
        
        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        
        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        
        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PROVISION_PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles
