name: Firebase deploy develop ios app

on:
  push:
    branches: [ 'main' ]

permissions:
  actions: write
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: "Clearly Legal - Dev"
  FLAVOR: "dev"

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - name: 📚 Checkout Repo
        uses: actions/checkout@v4

      - name: 📦 Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          dot_env: ${{ env.FLAVOR }}
          gh_access_token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Setup Apple Signing
        uses: ./.github/actions/apple-signing
        with:
          CERTIFICATE_BASE64: ${{ secrets.APPLE_SIGNING_CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}
          PROVISION_PROFILE_BASE64: ${{ secrets.APPLE_SIGNING_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_SIGNING_KEYCHAIN_PASSWORD }}

      - name: 🚧 Save service account content to json file
        working-directory: ./ios
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > firebase_service_account.json

      - name: 🚧 Install Pods
        working-directory: ./ios
        run: pod install

      - name: 🚀 Build & Deploy to Firebase
        working-directory: ./ios
        run: bundle exec fastlane firebase_deploy
        env:
          config: ${{ env.FLAVOR }}
